spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/hls_study
spring.datasource.username=hls_study
spring.datasource.password=hls_study
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
aws.s3.endpoint=http://localhost:9000
aws.s3.accessKeyId=minioadmin
aws.s3.secretAccessKey=minioadmin
aws.s3.bucketName=hls-study-videos
spring.jpa.hibernate.ddl-auto=update