spring.application.name=api
spring.datasource.url=jdbc:postgresql://localhost:5432/hls_study
spring.datasource.username=hls_study
spring.datasource.password=hls_study
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.jpa.hibernate.ddl-auto=update
# S3
aws.s3.endpoint=http://localhost:9000
aws.s3.accessKeyId=minioadmin
aws.s3.secretAccessKey=minioadmin
# Kafka - Configs
spring.kafka.bootstrap-servers=localhost:9092,localhost:9093,localhost:9094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.acks=all
# App - Video
app.video.bucket-name=hls-study-videos
app.video.uploaded-topic=videos.uploaded
app.video.kafka-send-timeout-seconds=10